# Add newline before each prompt line
SPACESHIP_PROMPT_ADD_NEWLINE=true

# Display username never
SPACESHIP_USER_SHOW=never

# Render asynchronously
SPACESHIP_PROMPT_ASYNC=true

# battery
SPACESHIP_BATTERY_SHOW=false

# directory
SPACESSHIP_DIR_TRUNC=4
SPACESHIP_DIR_TRUNC_REPO=true
SPACESHIP_DIR_TRUNC_PREFIX = .../

# exec_time
SPACESHIP_EXEC_TIME_ELAPSED=5
SPACESHIP_EXEC_TIME_PRECISION=3

# git
